/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSavingsRouteImport } from './routes/_authenticated/savings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPlatformAdminRouteImport } from './routes/_authenticated/platform-admin'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedApiRouteImport } from './routes/_authenticated/api'
import { Route as AuthenticatedAlcoRatesRouteImport } from './routes/_authenticated/alco-rates'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions.index'
import { Route as AuthenticatedSavingsIndexRouteImport } from './routes/_authenticated/savings.index'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedFdIndexRouteImport } from './routes/_authenticated/fd.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedTransactionsRepaymentRouteImport } from './routes/_authenticated/transactions.repayment'
import { Route as AuthenticatedTransactionsPaymentsRouteImport } from './routes/_authenticated/transactions.payments'
import { Route as AuthenticatedTransactionsDisbursementRouteImport } from './routes/_authenticated/transactions.disbursement'
import { Route as AuthenticatedTransactionsDepositWithdrawalRouteImport } from './routes/_authenticated/transactions.deposit-withdrawal'
import { Route as AuthenticatedTransactionsDepositReceiptRouteImport } from './routes/_authenticated/transactions.deposit-receipt'
import { Route as AuthenticatedTransactionsCloseCashierRouteImport } from './routes/_authenticated/transactions.close-cashier'
import { Route as AuthenticatedTransactionsChequeBankRouteImport } from './routes/_authenticated/transactions.cheque-bank'
import { Route as AuthenticatedTransactionsCashWalletRouteImport } from './routes/_authenticated/transactions.cash-wallet'
import { Route as AuthenticatedTransactionsCashBankRouteImport } from './routes/_authenticated/transactions.cash-bank'
import { Route as AuthenticatedSavingsPassbookRouteImport } from './routes/_authenticated/savings.passbook'
import { Route as AuthenticatedSavingsNewRouteImport } from './routes/_authenticated/savings.new'
import { Route as AuthenticatedSavingsCloseRouteImport } from './routes/_authenticated/savings.close'
import { Route as AuthenticatedLoansWriteOffRouteImport } from './routes/_authenticated/loans.write-off'
import { Route as AuthenticatedLoansTransferRouteImport } from './routes/_authenticated/loans.transfer'
import { Route as AuthenticatedLoansTerminationRouteImport } from './routes/_authenticated/loans.termination'
import { Route as AuthenticatedLoansRescheduleRouteImport } from './routes/_authenticated/loans.reschedule'
import { Route as AuthenticatedLoansNewRouteImport } from './routes/_authenticated/loans.new'
import { Route as AuthenticatedLoansLegalActionRouteImport } from './routes/_authenticated/loans.legal-action'
import { Route as AuthenticatedLoansDebitNoteRouteImport } from './routes/_authenticated/loans.debit-note'
import { Route as AuthenticatedFdNewRouteImport } from './routes/_authenticated/fd.new'
import { Route as AuthenticatedFdMaturityRouteImport } from './routes/_authenticated/fd.maturity'
import { Route as AuthenticatedFdIdRouteImport } from './routes/_authenticated/fd.$id'
import { Route as AuthenticatedCollectionsNewRouteImport } from './routes/_authenticated/collections.new'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedAccountsPaymentsRouteImport } from './routes/_authenticated/accounts.payments'
import { Route as AuthenticatedAccountsJournalRouteImport } from './routes/_authenticated/accounts.journal'
import { Route as AuthenticatedAccountsBulkJournalRouteImport } from './routes/_authenticated/accounts.bulk-journal'
import { Route as AuthenticatedAccountsBankReconciliationRouteImport } from './routes/_authenticated/accounts.bank-reconciliation'
import { Route as AuthenticatedAccountsPaymentsIndexRouteImport } from './routes/_authenticated/accounts.payments.index'
import { Route as AuthenticatedAccountsJournalIndexRouteImport } from './routes/_authenticated/accounts.journal.index'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as AuthenticatedAccountsPaymentsNewRouteImport } from './routes/_authenticated/accounts.payments.new'
import { Route as AuthenticatedAccountsJournalNewRouteImport } from './routes/_authenticated/accounts.journal.new'
import { Route as ApiPublicV1TransactionsOutboundRouteImport } from './routes/api/public/v1/transactions.outbound'
import { Route as ApiPublicV1TransactionsInboundRouteImport } from './routes/api/public/v1/transactions.inbound'
import { Route as ApiPublicV1IbTransactionRouteImport } from './routes/api/public/v1/ib.transaction'
import { Route as ApiPublicV1CribReportRouteImport } from './routes/api/public/v1/crib.report'
import { Route as ApiPublicV1CeftTransferRouteImport } from './routes/api/public/v1/ceft.transfer'
import { Route as ApiPublicV1AtmAuthorizeRouteImport } from './routes/api/public/v1/atm.authorize'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSavingsRoute = AuthenticatedSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformAdminRoute =
  AuthenticatedPlatformAdminRouteImport.update({
    id: '/platform-admin',
    path: '/platform-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiRoute = AuthenticatedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlcoRatesRoute = AuthenticatedAlcoRatesRouteImport.update({
  id: '/alco-rates',
  path: '/alco-rates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedSavingsIndexRoute =
  AuthenticatedSavingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSavingsRoute,
  } as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFdIndexRoute = AuthenticatedFdIndexRouteImport.update({
  id: '/fd/',
  path: '/fd/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsRepaymentRoute =
  AuthenticatedTransactionsRepaymentRouteImport.update({
    id: '/repayment',
    path: '/repayment',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsPaymentsRoute =
  AuthenticatedTransactionsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsDisbursementRoute =
  AuthenticatedTransactionsDisbursementRouteImport.update({
    id: '/disbursement',
    path: '/disbursement',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsDepositWithdrawalRoute =
  AuthenticatedTransactionsDepositWithdrawalRouteImport.update({
    id: '/deposit-withdrawal',
    path: '/deposit-withdrawal',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsDepositReceiptRoute =
  AuthenticatedTransactionsDepositReceiptRouteImport.update({
    id: '/deposit-receipt',
    path: '/deposit-receipt',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsCloseCashierRoute =
  AuthenticatedTransactionsCloseCashierRouteImport.update({
    id: '/close-cashier',
    path: '/close-cashier',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsChequeBankRoute =
  AuthenticatedTransactionsChequeBankRouteImport.update({
    id: '/cheque-bank',
    path: '/cheque-bank',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsCashWalletRoute =
  AuthenticatedTransactionsCashWalletRouteImport.update({
    id: '/cash-wallet',
    path: '/cash-wallet',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsCashBankRoute =
  AuthenticatedTransactionsCashBankRouteImport.update({
    id: '/cash-bank',
    path: '/cash-bank',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedSavingsPassbookRoute =
  AuthenticatedSavingsPassbookRouteImport.update({
    id: '/passbook',
    path: '/passbook',
    getParentRoute: () => AuthenticatedSavingsRoute,
  } as any)
const AuthenticatedSavingsNewRoute = AuthenticatedSavingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSavingsRoute,
} as any)
const AuthenticatedSavingsCloseRoute =
  AuthenticatedSavingsCloseRouteImport.update({
    id: '/close',
    path: '/close',
    getParentRoute: () => AuthenticatedSavingsRoute,
  } as any)
const AuthenticatedLoansWriteOffRoute =
  AuthenticatedLoansWriteOffRouteImport.update({
    id: '/loans/write-off',
    path: '/loans/write-off',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansTransferRoute =
  AuthenticatedLoansTransferRouteImport.update({
    id: '/loans/transfer',
    path: '/loans/transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansTerminationRoute =
  AuthenticatedLoansTerminationRouteImport.update({
    id: '/loans/termination',
    path: '/loans/termination',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansRescheduleRoute =
  AuthenticatedLoansRescheduleRouteImport.update({
    id: '/loans/reschedule',
    path: '/loans/reschedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansNewRoute = AuthenticatedLoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoansLegalActionRoute =
  AuthenticatedLoansLegalActionRouteImport.update({
    id: '/loans/legal-action',
    path: '/loans/legal-action',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansDebitNoteRoute =
  AuthenticatedLoansDebitNoteRouteImport.update({
    id: '/loans/debit-note',
    path: '/loans/debit-note',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFdNewRoute = AuthenticatedFdNewRouteImport.update({
  id: '/fd/new',
  path: '/fd/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFdMaturityRoute = AuthenticatedFdMaturityRouteImport.update({
  id: '/fd/maturity',
  path: '/fd/maturity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFdIdRoute = AuthenticatedFdIdRouteImport.update({
  id: '/fd/$id',
  path: '/fd/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsNewRoute =
  AuthenticatedCollectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsPaymentsRoute =
  AuthenticatedAccountsPaymentsRouteImport.update({
    id: '/accounts/payments',
    path: '/accounts/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsJournalRoute =
  AuthenticatedAccountsJournalRouteImport.update({
    id: '/accounts/journal',
    path: '/accounts/journal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsBulkJournalRoute =
  AuthenticatedAccountsBulkJournalRouteImport.update({
    id: '/accounts/bulk-journal',
    path: '/accounts/bulk-journal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsBankReconciliationRoute =
  AuthenticatedAccountsBankReconciliationRouteImport.update({
    id: '/accounts/bank-reconciliation',
    path: '/accounts/bank-reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsPaymentsIndexRoute =
  AuthenticatedAccountsPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountsPaymentsRoute,
  } as any)
const AuthenticatedAccountsJournalIndexRoute =
  AuthenticatedAccountsJournalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountsJournalRoute,
  } as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsPaymentsNewRoute =
  AuthenticatedAccountsPaymentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsPaymentsRoute,
  } as any)
const AuthenticatedAccountsJournalNewRoute =
  AuthenticatedAccountsJournalNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsJournalRoute,
  } as any)
const ApiPublicV1TransactionsOutboundRoute =
  ApiPublicV1TransactionsOutboundRouteImport.update({
    id: '/api/public/v1/transactions/outbound',
    path: '/api/public/v1/transactions/outbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TransactionsInboundRoute =
  ApiPublicV1TransactionsInboundRouteImport.update({
    id: '/api/public/v1/transactions/inbound',
    path: '/api/public/v1/transactions/inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1IbTransactionRoute =
  ApiPublicV1IbTransactionRouteImport.update({
    id: '/api/public/v1/ib/transaction',
    path: '/api/public/v1/ib/transaction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1CribReportRoute = ApiPublicV1CribReportRouteImport.update({
  id: '/api/public/v1/crib/report',
  path: '/api/public/v1/crib/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CeftTransferRoute = ApiPublicV1CeftTransferRouteImport.update({
  id: '/api/public/v1/ceft/transfer',
  path: '/api/public/v1/ceft/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AtmAuthorizeRoute = ApiPublicV1AtmAuthorizeRouteImport.update({
  id: '/api/public/v1/atm/authorize',
  path: '/api/public/v1/atm/authorize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alco-rates': typeof AuthenticatedAlcoRatesRoute
  '/api': typeof AuthenticatedApiRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/savings': typeof AuthenticatedSavingsRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/accounts/bank-reconciliation': typeof AuthenticatedAccountsBankReconciliationRoute
  '/accounts/bulk-journal': typeof AuthenticatedAccountsBulkJournalRoute
  '/accounts/journal': typeof AuthenticatedAccountsJournalRouteWithChildren
  '/accounts/payments': typeof AuthenticatedAccountsPaymentsRouteWithChildren
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/fd/$id': typeof AuthenticatedFdIdRoute
  '/fd/maturity': typeof AuthenticatedFdMaturityRoute
  '/fd/new': typeof AuthenticatedFdNewRoute
  '/loans/debit-note': typeof AuthenticatedLoansDebitNoteRoute
  '/loans/legal-action': typeof AuthenticatedLoansLegalActionRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/loans/reschedule': typeof AuthenticatedLoansRescheduleRoute
  '/loans/termination': typeof AuthenticatedLoansTerminationRoute
  '/loans/transfer': typeof AuthenticatedLoansTransferRoute
  '/loans/write-off': typeof AuthenticatedLoansWriteOffRoute
  '/savings/close': typeof AuthenticatedSavingsCloseRoute
  '/savings/new': typeof AuthenticatedSavingsNewRoute
  '/savings/passbook': typeof AuthenticatedSavingsPassbookRoute
  '/transactions/cash-bank': typeof AuthenticatedTransactionsCashBankRoute
  '/transactions/cash-wallet': typeof AuthenticatedTransactionsCashWalletRoute
  '/transactions/cheque-bank': typeof AuthenticatedTransactionsChequeBankRoute
  '/transactions/close-cashier': typeof AuthenticatedTransactionsCloseCashierRoute
  '/transactions/deposit-receipt': typeof AuthenticatedTransactionsDepositReceiptRoute
  '/transactions/deposit-withdrawal': typeof AuthenticatedTransactionsDepositWithdrawalRoute
  '/transactions/disbursement': typeof AuthenticatedTransactionsDisbursementRoute
  '/transactions/payments': typeof AuthenticatedTransactionsPaymentsRoute
  '/transactions/repayment': typeof AuthenticatedTransactionsRepaymentRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/fd/': typeof AuthenticatedFdIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/loans/': typeof AuthenticatedLoansIndexRoute
  '/savings/': typeof AuthenticatedSavingsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/accounts/journal/new': typeof AuthenticatedAccountsJournalNewRoute
  '/accounts/payments/new': typeof AuthenticatedAccountsPaymentsNewRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/accounts/journal/': typeof AuthenticatedAccountsJournalIndexRoute
  '/accounts/payments/': typeof AuthenticatedAccountsPaymentsIndexRoute
  '/api/public/v1/atm/authorize': typeof ApiPublicV1AtmAuthorizeRoute
  '/api/public/v1/ceft/transfer': typeof ApiPublicV1CeftTransferRoute
  '/api/public/v1/crib/report': typeof ApiPublicV1CribReportRoute
  '/api/public/v1/ib/transaction': typeof ApiPublicV1IbTransactionRoute
  '/api/public/v1/transactions/inbound': typeof ApiPublicV1TransactionsInboundRoute
  '/api/public/v1/transactions/outbound': typeof ApiPublicV1TransactionsOutboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alco-rates': typeof AuthenticatedAlcoRatesRoute
  '/api': typeof AuthenticatedApiRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/accounts/bank-reconciliation': typeof AuthenticatedAccountsBankReconciliationRoute
  '/accounts/bulk-journal': typeof AuthenticatedAccountsBulkJournalRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/fd/$id': typeof AuthenticatedFdIdRoute
  '/fd/maturity': typeof AuthenticatedFdMaturityRoute
  '/fd/new': typeof AuthenticatedFdNewRoute
  '/loans/debit-note': typeof AuthenticatedLoansDebitNoteRoute
  '/loans/legal-action': typeof AuthenticatedLoansLegalActionRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/loans/reschedule': typeof AuthenticatedLoansRescheduleRoute
  '/loans/termination': typeof AuthenticatedLoansTerminationRoute
  '/loans/transfer': typeof AuthenticatedLoansTransferRoute
  '/loans/write-off': typeof AuthenticatedLoansWriteOffRoute
  '/savings/close': typeof AuthenticatedSavingsCloseRoute
  '/savings/new': typeof AuthenticatedSavingsNewRoute
  '/savings/passbook': typeof AuthenticatedSavingsPassbookRoute
  '/transactions/cash-bank': typeof AuthenticatedTransactionsCashBankRoute
  '/transactions/cash-wallet': typeof AuthenticatedTransactionsCashWalletRoute
  '/transactions/cheque-bank': typeof AuthenticatedTransactionsChequeBankRoute
  '/transactions/close-cashier': typeof AuthenticatedTransactionsCloseCashierRoute
  '/transactions/deposit-receipt': typeof AuthenticatedTransactionsDepositReceiptRoute
  '/transactions/deposit-withdrawal': typeof AuthenticatedTransactionsDepositWithdrawalRoute
  '/transactions/disbursement': typeof AuthenticatedTransactionsDisbursementRoute
  '/transactions/payments': typeof AuthenticatedTransactionsPaymentsRoute
  '/transactions/repayment': typeof AuthenticatedTransactionsRepaymentRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/fd': typeof AuthenticatedFdIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
  '/savings': typeof AuthenticatedSavingsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/accounts/journal/new': typeof AuthenticatedAccountsJournalNewRoute
  '/accounts/payments/new': typeof AuthenticatedAccountsPaymentsNewRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/accounts/journal': typeof AuthenticatedAccountsJournalIndexRoute
  '/accounts/payments': typeof AuthenticatedAccountsPaymentsIndexRoute
  '/api/public/v1/atm/authorize': typeof ApiPublicV1AtmAuthorizeRoute
  '/api/public/v1/ceft/transfer': typeof ApiPublicV1CeftTransferRoute
  '/api/public/v1/crib/report': typeof ApiPublicV1CribReportRoute
  '/api/public/v1/ib/transaction': typeof ApiPublicV1IbTransactionRoute
  '/api/public/v1/transactions/inbound': typeof ApiPublicV1TransactionsInboundRoute
  '/api/public/v1/transactions/outbound': typeof ApiPublicV1TransactionsOutboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alco-rates': typeof AuthenticatedAlcoRatesRoute
  '/_authenticated/api': typeof AuthenticatedApiRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/savings': typeof AuthenticatedSavingsRouteWithChildren
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/_authenticated/accounts/bank-reconciliation': typeof AuthenticatedAccountsBankReconciliationRoute
  '/_authenticated/accounts/bulk-journal': typeof AuthenticatedAccountsBulkJournalRoute
  '/_authenticated/accounts/journal': typeof AuthenticatedAccountsJournalRouteWithChildren
  '/_authenticated/accounts/payments': typeof AuthenticatedAccountsPaymentsRouteWithChildren
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/_authenticated/fd/$id': typeof AuthenticatedFdIdRoute
  '/_authenticated/fd/maturity': typeof AuthenticatedFdMaturityRoute
  '/_authenticated/fd/new': typeof AuthenticatedFdNewRoute
  '/_authenticated/loans/debit-note': typeof AuthenticatedLoansDebitNoteRoute
  '/_authenticated/loans/legal-action': typeof AuthenticatedLoansLegalActionRoute
  '/_authenticated/loans/new': typeof AuthenticatedLoansNewRoute
  '/_authenticated/loans/reschedule': typeof AuthenticatedLoansRescheduleRoute
  '/_authenticated/loans/termination': typeof AuthenticatedLoansTerminationRoute
  '/_authenticated/loans/transfer': typeof AuthenticatedLoansTransferRoute
  '/_authenticated/loans/write-off': typeof AuthenticatedLoansWriteOffRoute
  '/_authenticated/savings/close': typeof AuthenticatedSavingsCloseRoute
  '/_authenticated/savings/new': typeof AuthenticatedSavingsNewRoute
  '/_authenticated/savings/passbook': typeof AuthenticatedSavingsPassbookRoute
  '/_authenticated/transactions/cash-bank': typeof AuthenticatedTransactionsCashBankRoute
  '/_authenticated/transactions/cash-wallet': typeof AuthenticatedTransactionsCashWalletRoute
  '/_authenticated/transactions/cheque-bank': typeof AuthenticatedTransactionsChequeBankRoute
  '/_authenticated/transactions/close-cashier': typeof AuthenticatedTransactionsCloseCashierRoute
  '/_authenticated/transactions/deposit-receipt': typeof AuthenticatedTransactionsDepositReceiptRoute
  '/_authenticated/transactions/deposit-withdrawal': typeof AuthenticatedTransactionsDepositWithdrawalRoute
  '/_authenticated/transactions/disbursement': typeof AuthenticatedTransactionsDisbursementRoute
  '/_authenticated/transactions/payments': typeof AuthenticatedTransactionsPaymentsRoute
  '/_authenticated/transactions/repayment': typeof AuthenticatedTransactionsRepaymentRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/fd/': typeof AuthenticatedFdIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
  '/_authenticated/savings/': typeof AuthenticatedSavingsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/accounts/journal/new': typeof AuthenticatedAccountsJournalNewRoute
  '/_authenticated/accounts/payments/new': typeof AuthenticatedAccountsPaymentsNewRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/_authenticated/accounts/journal/': typeof AuthenticatedAccountsJournalIndexRoute
  '/_authenticated/accounts/payments/': typeof AuthenticatedAccountsPaymentsIndexRoute
  '/api/public/v1/atm/authorize': typeof ApiPublicV1AtmAuthorizeRoute
  '/api/public/v1/ceft/transfer': typeof ApiPublicV1CeftTransferRoute
  '/api/public/v1/crib/report': typeof ApiPublicV1CribReportRoute
  '/api/public/v1/ib/transaction': typeof ApiPublicV1IbTransactionRoute
  '/api/public/v1/transactions/inbound': typeof ApiPublicV1TransactionsInboundRoute
  '/api/public/v1/transactions/outbound': typeof ApiPublicV1TransactionsOutboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/alco-rates'
    | '/api'
    | '/approvals'
    | '/collections'
    | '/dashboard'
    | '/ledger'
    | '/platform-admin'
    | '/reports'
    | '/savings'
    | '/transactions'
    | '/workflows'
    | '/accounts/bank-reconciliation'
    | '/accounts/bulk-journal'
    | '/accounts/journal'
    | '/accounts/payments'
    | '/clients/$id'
    | '/clients/new'
    | '/collections/new'
    | '/fd/$id'
    | '/fd/maturity'
    | '/fd/new'
    | '/loans/debit-note'
    | '/loans/legal-action'
    | '/loans/new'
    | '/loans/reschedule'
    | '/loans/termination'
    | '/loans/transfer'
    | '/loans/write-off'
    | '/savings/close'
    | '/savings/new'
    | '/savings/passbook'
    | '/transactions/cash-bank'
    | '/transactions/cash-wallet'
    | '/transactions/cheque-bank'
    | '/transactions/close-cashier'
    | '/transactions/deposit-receipt'
    | '/transactions/deposit-withdrawal'
    | '/transactions/disbursement'
    | '/transactions/payments'
    | '/transactions/repayment'
    | '/accounts/'
    | '/clients/'
    | '/fd/'
    | '/groups/'
    | '/loans/'
    | '/savings/'
    | '/transactions/'
    | '/accounts/journal/new'
    | '/accounts/payments/new'
    | '/api/public/v1/health'
    | '/accounts/journal/'
    | '/accounts/payments/'
    | '/api/public/v1/atm/authorize'
    | '/api/public/v1/ceft/transfer'
    | '/api/public/v1/crib/report'
    | '/api/public/v1/ib/transaction'
    | '/api/public/v1/transactions/inbound'
    | '/api/public/v1/transactions/outbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/alco-rates'
    | '/api'
    | '/approvals'
    | '/collections'
    | '/dashboard'
    | '/ledger'
    | '/platform-admin'
    | '/reports'
    | '/workflows'
    | '/accounts/bank-reconciliation'
    | '/accounts/bulk-journal'
    | '/clients/$id'
    | '/clients/new'
    | '/collections/new'
    | '/fd/$id'
    | '/fd/maturity'
    | '/fd/new'
    | '/loans/debit-note'
    | '/loans/legal-action'
    | '/loans/new'
    | '/loans/reschedule'
    | '/loans/termination'
    | '/loans/transfer'
    | '/loans/write-off'
    | '/savings/close'
    | '/savings/new'
    | '/savings/passbook'
    | '/transactions/cash-bank'
    | '/transactions/cash-wallet'
    | '/transactions/cheque-bank'
    | '/transactions/close-cashier'
    | '/transactions/deposit-receipt'
    | '/transactions/deposit-withdrawal'
    | '/transactions/disbursement'
    | '/transactions/payments'
    | '/transactions/repayment'
    | '/accounts'
    | '/clients'
    | '/fd'
    | '/groups'
    | '/loans'
    | '/savings'
    | '/transactions'
    | '/accounts/journal/new'
    | '/accounts/payments/new'
    | '/api/public/v1/health'
    | '/accounts/journal'
    | '/accounts/payments'
    | '/api/public/v1/atm/authorize'
    | '/api/public/v1/ceft/transfer'
    | '/api/public/v1/crib/report'
    | '/api/public/v1/ib/transaction'
    | '/api/public/v1/transactions/inbound'
    | '/api/public/v1/transactions/outbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/alco-rates'
    | '/_authenticated/api'
    | '/_authenticated/approvals'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/ledger'
    | '/_authenticated/platform-admin'
    | '/_authenticated/reports'
    | '/_authenticated/savings'
    | '/_authenticated/transactions'
    | '/_authenticated/workflows'
    | '/_authenticated/accounts/bank-reconciliation'
    | '/_authenticated/accounts/bulk-journal'
    | '/_authenticated/accounts/journal'
    | '/_authenticated/accounts/payments'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/collections/new'
    | '/_authenticated/fd/$id'
    | '/_authenticated/fd/maturity'
    | '/_authenticated/fd/new'
    | '/_authenticated/loans/debit-note'
    | '/_authenticated/loans/legal-action'
    | '/_authenticated/loans/new'
    | '/_authenticated/loans/reschedule'
    | '/_authenticated/loans/termination'
    | '/_authenticated/loans/transfer'
    | '/_authenticated/loans/write-off'
    | '/_authenticated/savings/close'
    | '/_authenticated/savings/new'
    | '/_authenticated/savings/passbook'
    | '/_authenticated/transactions/cash-bank'
    | '/_authenticated/transactions/cash-wallet'
    | '/_authenticated/transactions/cheque-bank'
    | '/_authenticated/transactions/close-cashier'
    | '/_authenticated/transactions/deposit-receipt'
    | '/_authenticated/transactions/deposit-withdrawal'
    | '/_authenticated/transactions/disbursement'
    | '/_authenticated/transactions/payments'
    | '/_authenticated/transactions/repayment'
    | '/_authenticated/accounts/'
    | '/_authenticated/clients/'
    | '/_authenticated/fd/'
    | '/_authenticated/groups/'
    | '/_authenticated/loans/'
    | '/_authenticated/savings/'
    | '/_authenticated/transactions/'
    | '/_authenticated/accounts/journal/new'
    | '/_authenticated/accounts/payments/new'
    | '/api/public/v1/health'
    | '/_authenticated/accounts/journal/'
    | '/_authenticated/accounts/payments/'
    | '/api/public/v1/atm/authorize'
    | '/api/public/v1/ceft/transfer'
    | '/api/public/v1/crib/report'
    | '/api/public/v1/ib/transaction'
    | '/api/public/v1/transactions/inbound'
    | '/api/public/v1/transactions/outbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1AtmAuthorizeRoute: typeof ApiPublicV1AtmAuthorizeRoute
  ApiPublicV1CeftTransferRoute: typeof ApiPublicV1CeftTransferRoute
  ApiPublicV1CribReportRoute: typeof ApiPublicV1CribReportRoute
  ApiPublicV1IbTransactionRoute: typeof ApiPublicV1IbTransactionRoute
  ApiPublicV1TransactionsInboundRoute: typeof ApiPublicV1TransactionsInboundRoute
  ApiPublicV1TransactionsOutboundRoute: typeof ApiPublicV1TransactionsOutboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/savings': {
      id: '/_authenticated/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AuthenticatedSavingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-admin': {
      id: '/_authenticated/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof AuthenticatedPlatformAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api': {
      id: '/_authenticated/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AuthenticatedApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alco-rates': {
      id: '/_authenticated/alco-rates'
      path: '/alco-rates'
      fullPath: '/alco-rates'
      preLoaderRoute: typeof AuthenticatedAlcoRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/savings/': {
      id: '/_authenticated/savings/'
      path: '/'
      fullPath: '/savings/'
      preLoaderRoute: typeof AuthenticatedSavingsIndexRouteImport
      parentRoute: typeof AuthenticatedSavingsRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fd/': {
      id: '/_authenticated/fd/'
      path: '/fd'
      fullPath: '/fd/'
      preLoaderRoute: typeof AuthenticatedFdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/repayment': {
      id: '/_authenticated/transactions/repayment'
      path: '/repayment'
      fullPath: '/transactions/repayment'
      preLoaderRoute: typeof AuthenticatedTransactionsRepaymentRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/payments': {
      id: '/_authenticated/transactions/payments'
      path: '/payments'
      fullPath: '/transactions/payments'
      preLoaderRoute: typeof AuthenticatedTransactionsPaymentsRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/disbursement': {
      id: '/_authenticated/transactions/disbursement'
      path: '/disbursement'
      fullPath: '/transactions/disbursement'
      preLoaderRoute: typeof AuthenticatedTransactionsDisbursementRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/deposit-withdrawal': {
      id: '/_authenticated/transactions/deposit-withdrawal'
      path: '/deposit-withdrawal'
      fullPath: '/transactions/deposit-withdrawal'
      preLoaderRoute: typeof AuthenticatedTransactionsDepositWithdrawalRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/deposit-receipt': {
      id: '/_authenticated/transactions/deposit-receipt'
      path: '/deposit-receipt'
      fullPath: '/transactions/deposit-receipt'
      preLoaderRoute: typeof AuthenticatedTransactionsDepositReceiptRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/close-cashier': {
      id: '/_authenticated/transactions/close-cashier'
      path: '/close-cashier'
      fullPath: '/transactions/close-cashier'
      preLoaderRoute: typeof AuthenticatedTransactionsCloseCashierRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/cheque-bank': {
      id: '/_authenticated/transactions/cheque-bank'
      path: '/cheque-bank'
      fullPath: '/transactions/cheque-bank'
      preLoaderRoute: typeof AuthenticatedTransactionsChequeBankRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/cash-wallet': {
      id: '/_authenticated/transactions/cash-wallet'
      path: '/cash-wallet'
      fullPath: '/transactions/cash-wallet'
      preLoaderRoute: typeof AuthenticatedTransactionsCashWalletRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/cash-bank': {
      id: '/_authenticated/transactions/cash-bank'
      path: '/cash-bank'
      fullPath: '/transactions/cash-bank'
      preLoaderRoute: typeof AuthenticatedTransactionsCashBankRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/savings/passbook': {
      id: '/_authenticated/savings/passbook'
      path: '/passbook'
      fullPath: '/savings/passbook'
      preLoaderRoute: typeof AuthenticatedSavingsPassbookRouteImport
      parentRoute: typeof AuthenticatedSavingsRoute
    }
    '/_authenticated/savings/new': {
      id: '/_authenticated/savings/new'
      path: '/new'
      fullPath: '/savings/new'
      preLoaderRoute: typeof AuthenticatedSavingsNewRouteImport
      parentRoute: typeof AuthenticatedSavingsRoute
    }
    '/_authenticated/savings/close': {
      id: '/_authenticated/savings/close'
      path: '/close'
      fullPath: '/savings/close'
      preLoaderRoute: typeof AuthenticatedSavingsCloseRouteImport
      parentRoute: typeof AuthenticatedSavingsRoute
    }
    '/_authenticated/loans/write-off': {
      id: '/_authenticated/loans/write-off'
      path: '/loans/write-off'
      fullPath: '/loans/write-off'
      preLoaderRoute: typeof AuthenticatedLoansWriteOffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/transfer': {
      id: '/_authenticated/loans/transfer'
      path: '/loans/transfer'
      fullPath: '/loans/transfer'
      preLoaderRoute: typeof AuthenticatedLoansTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/termination': {
      id: '/_authenticated/loans/termination'
      path: '/loans/termination'
      fullPath: '/loans/termination'
      preLoaderRoute: typeof AuthenticatedLoansTerminationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/reschedule': {
      id: '/_authenticated/loans/reschedule'
      path: '/loans/reschedule'
      fullPath: '/loans/reschedule'
      preLoaderRoute: typeof AuthenticatedLoansRescheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/new': {
      id: '/_authenticated/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof AuthenticatedLoansNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/legal-action': {
      id: '/_authenticated/loans/legal-action'
      path: '/loans/legal-action'
      fullPath: '/loans/legal-action'
      preLoaderRoute: typeof AuthenticatedLoansLegalActionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/debit-note': {
      id: '/_authenticated/loans/debit-note'
      path: '/loans/debit-note'
      fullPath: '/loans/debit-note'
      preLoaderRoute: typeof AuthenticatedLoansDebitNoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fd/new': {
      id: '/_authenticated/fd/new'
      path: '/fd/new'
      fullPath: '/fd/new'
      preLoaderRoute: typeof AuthenticatedFdNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fd/maturity': {
      id: '/_authenticated/fd/maturity'
      path: '/fd/maturity'
      fullPath: '/fd/maturity'
      preLoaderRoute: typeof AuthenticatedFdMaturityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fd/$id': {
      id: '/_authenticated/fd/$id'
      path: '/fd/$id'
      fullPath: '/fd/$id'
      preLoaderRoute: typeof AuthenticatedFdIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections/new': {
      id: '/_authenticated/collections/new'
      path: '/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof AuthenticatedCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/payments': {
      id: '/_authenticated/accounts/payments'
      path: '/accounts/payments'
      fullPath: '/accounts/payments'
      preLoaderRoute: typeof AuthenticatedAccountsPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/journal': {
      id: '/_authenticated/accounts/journal'
      path: '/accounts/journal'
      fullPath: '/accounts/journal'
      preLoaderRoute: typeof AuthenticatedAccountsJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/bulk-journal': {
      id: '/_authenticated/accounts/bulk-journal'
      path: '/accounts/bulk-journal'
      fullPath: '/accounts/bulk-journal'
      preLoaderRoute: typeof AuthenticatedAccountsBulkJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/bank-reconciliation': {
      id: '/_authenticated/accounts/bank-reconciliation'
      path: '/accounts/bank-reconciliation'
      fullPath: '/accounts/bank-reconciliation'
      preLoaderRoute: typeof AuthenticatedAccountsBankReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/payments/': {
      id: '/_authenticated/accounts/payments/'
      path: '/'
      fullPath: '/accounts/payments/'
      preLoaderRoute: typeof AuthenticatedAccountsPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountsPaymentsRoute
    }
    '/_authenticated/accounts/journal/': {
      id: '/_authenticated/accounts/journal/'
      path: '/'
      fullPath: '/accounts/journal/'
      preLoaderRoute: typeof AuthenticatedAccountsJournalIndexRouteImport
      parentRoute: typeof AuthenticatedAccountsJournalRoute
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts/payments/new': {
      id: '/_authenticated/accounts/payments/new'
      path: '/new'
      fullPath: '/accounts/payments/new'
      preLoaderRoute: typeof AuthenticatedAccountsPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedAccountsPaymentsRoute
    }
    '/_authenticated/accounts/journal/new': {
      id: '/_authenticated/accounts/journal/new'
      path: '/new'
      fullPath: '/accounts/journal/new'
      preLoaderRoute: typeof AuthenticatedAccountsJournalNewRouteImport
      parentRoute: typeof AuthenticatedAccountsJournalRoute
    }
    '/api/public/v1/transactions/outbound': {
      id: '/api/public/v1/transactions/outbound'
      path: '/api/public/v1/transactions/outbound'
      fullPath: '/api/public/v1/transactions/outbound'
      preLoaderRoute: typeof ApiPublicV1TransactionsOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/transactions/inbound': {
      id: '/api/public/v1/transactions/inbound'
      path: '/api/public/v1/transactions/inbound'
      fullPath: '/api/public/v1/transactions/inbound'
      preLoaderRoute: typeof ApiPublicV1TransactionsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ib/transaction': {
      id: '/api/public/v1/ib/transaction'
      path: '/api/public/v1/ib/transaction'
      fullPath: '/api/public/v1/ib/transaction'
      preLoaderRoute: typeof ApiPublicV1IbTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/crib/report': {
      id: '/api/public/v1/crib/report'
      path: '/api/public/v1/crib/report'
      fullPath: '/api/public/v1/crib/report'
      preLoaderRoute: typeof ApiPublicV1CribReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ceft/transfer': {
      id: '/api/public/v1/ceft/transfer'
      path: '/api/public/v1/ceft/transfer'
      fullPath: '/api/public/v1/ceft/transfer'
      preLoaderRoute: typeof ApiPublicV1CeftTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/atm/authorize': {
      id: '/api/public/v1/atm/authorize'
      path: '/api/public/v1/atm/authorize'
      fullPath: '/api/public/v1/atm/authorize'
      preLoaderRoute: typeof ApiPublicV1AtmAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCollectionsRouteChildren {
  AuthenticatedCollectionsNewRoute: typeof AuthenticatedCollectionsNewRoute
}

const AuthenticatedCollectionsRouteChildren: AuthenticatedCollectionsRouteChildren =
  {
    AuthenticatedCollectionsNewRoute: AuthenticatedCollectionsNewRoute,
  }

const AuthenticatedCollectionsRouteWithChildren =
  AuthenticatedCollectionsRoute._addFileChildren(
    AuthenticatedCollectionsRouteChildren,
  )

interface AuthenticatedSavingsRouteChildren {
  AuthenticatedSavingsCloseRoute: typeof AuthenticatedSavingsCloseRoute
  AuthenticatedSavingsNewRoute: typeof AuthenticatedSavingsNewRoute
  AuthenticatedSavingsPassbookRoute: typeof AuthenticatedSavingsPassbookRoute
  AuthenticatedSavingsIndexRoute: typeof AuthenticatedSavingsIndexRoute
}

const AuthenticatedSavingsRouteChildren: AuthenticatedSavingsRouteChildren = {
  AuthenticatedSavingsCloseRoute: AuthenticatedSavingsCloseRoute,
  AuthenticatedSavingsNewRoute: AuthenticatedSavingsNewRoute,
  AuthenticatedSavingsPassbookRoute: AuthenticatedSavingsPassbookRoute,
  AuthenticatedSavingsIndexRoute: AuthenticatedSavingsIndexRoute,
}

const AuthenticatedSavingsRouteWithChildren =
  AuthenticatedSavingsRoute._addFileChildren(AuthenticatedSavingsRouteChildren)

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsCashBankRoute: typeof AuthenticatedTransactionsCashBankRoute
  AuthenticatedTransactionsCashWalletRoute: typeof AuthenticatedTransactionsCashWalletRoute
  AuthenticatedTransactionsChequeBankRoute: typeof AuthenticatedTransactionsChequeBankRoute
  AuthenticatedTransactionsCloseCashierRoute: typeof AuthenticatedTransactionsCloseCashierRoute
  AuthenticatedTransactionsDepositReceiptRoute: typeof AuthenticatedTransactionsDepositReceiptRoute
  AuthenticatedTransactionsDepositWithdrawalRoute: typeof AuthenticatedTransactionsDepositWithdrawalRoute
  AuthenticatedTransactionsDisbursementRoute: typeof AuthenticatedTransactionsDisbursementRoute
  AuthenticatedTransactionsPaymentsRoute: typeof AuthenticatedTransactionsPaymentsRoute
  AuthenticatedTransactionsRepaymentRoute: typeof AuthenticatedTransactionsRepaymentRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsCashBankRoute:
      AuthenticatedTransactionsCashBankRoute,
    AuthenticatedTransactionsCashWalletRoute:
      AuthenticatedTransactionsCashWalletRoute,
    AuthenticatedTransactionsChequeBankRoute:
      AuthenticatedTransactionsChequeBankRoute,
    AuthenticatedTransactionsCloseCashierRoute:
      AuthenticatedTransactionsCloseCashierRoute,
    AuthenticatedTransactionsDepositReceiptRoute:
      AuthenticatedTransactionsDepositReceiptRoute,
    AuthenticatedTransactionsDepositWithdrawalRoute:
      AuthenticatedTransactionsDepositWithdrawalRoute,
    AuthenticatedTransactionsDisbursementRoute:
      AuthenticatedTransactionsDisbursementRoute,
    AuthenticatedTransactionsPaymentsRoute:
      AuthenticatedTransactionsPaymentsRoute,
    AuthenticatedTransactionsRepaymentRoute:
      AuthenticatedTransactionsRepaymentRoute,
    AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedAccountsJournalRouteChildren {
  AuthenticatedAccountsJournalNewRoute: typeof AuthenticatedAccountsJournalNewRoute
  AuthenticatedAccountsJournalIndexRoute: typeof AuthenticatedAccountsJournalIndexRoute
}

const AuthenticatedAccountsJournalRouteChildren: AuthenticatedAccountsJournalRouteChildren =
  {
    AuthenticatedAccountsJournalNewRoute: AuthenticatedAccountsJournalNewRoute,
    AuthenticatedAccountsJournalIndexRoute:
      AuthenticatedAccountsJournalIndexRoute,
  }

const AuthenticatedAccountsJournalRouteWithChildren =
  AuthenticatedAccountsJournalRoute._addFileChildren(
    AuthenticatedAccountsJournalRouteChildren,
  )

interface AuthenticatedAccountsPaymentsRouteChildren {
  AuthenticatedAccountsPaymentsNewRoute: typeof AuthenticatedAccountsPaymentsNewRoute
  AuthenticatedAccountsPaymentsIndexRoute: typeof AuthenticatedAccountsPaymentsIndexRoute
}

const AuthenticatedAccountsPaymentsRouteChildren: AuthenticatedAccountsPaymentsRouteChildren =
  {
    AuthenticatedAccountsPaymentsNewRoute:
      AuthenticatedAccountsPaymentsNewRoute,
    AuthenticatedAccountsPaymentsIndexRoute:
      AuthenticatedAccountsPaymentsIndexRoute,
  }

const AuthenticatedAccountsPaymentsRouteWithChildren =
  AuthenticatedAccountsPaymentsRoute._addFileChildren(
    AuthenticatedAccountsPaymentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlcoRatesRoute: typeof AuthenticatedAlcoRatesRoute
  AuthenticatedApiRoute: typeof AuthenticatedApiRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedPlatformAdminRoute: typeof AuthenticatedPlatformAdminRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSavingsRoute: typeof AuthenticatedSavingsRouteWithChildren
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedAccountsBankReconciliationRoute: typeof AuthenticatedAccountsBankReconciliationRoute
  AuthenticatedAccountsBulkJournalRoute: typeof AuthenticatedAccountsBulkJournalRoute
  AuthenticatedAccountsJournalRoute: typeof AuthenticatedAccountsJournalRouteWithChildren
  AuthenticatedAccountsPaymentsRoute: typeof AuthenticatedAccountsPaymentsRouteWithChildren
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedFdIdRoute: typeof AuthenticatedFdIdRoute
  AuthenticatedFdMaturityRoute: typeof AuthenticatedFdMaturityRoute
  AuthenticatedFdNewRoute: typeof AuthenticatedFdNewRoute
  AuthenticatedLoansDebitNoteRoute: typeof AuthenticatedLoansDebitNoteRoute
  AuthenticatedLoansLegalActionRoute: typeof AuthenticatedLoansLegalActionRoute
  AuthenticatedLoansNewRoute: typeof AuthenticatedLoansNewRoute
  AuthenticatedLoansRescheduleRoute: typeof AuthenticatedLoansRescheduleRoute
  AuthenticatedLoansTerminationRoute: typeof AuthenticatedLoansTerminationRoute
  AuthenticatedLoansTransferRoute: typeof AuthenticatedLoansTransferRoute
  AuthenticatedLoansWriteOffRoute: typeof AuthenticatedLoansWriteOffRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedFdIndexRoute: typeof AuthenticatedFdIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlcoRatesRoute: AuthenticatedAlcoRatesRoute,
  AuthenticatedApiRoute: AuthenticatedApiRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedPlatformAdminRoute: AuthenticatedPlatformAdminRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSavingsRoute: AuthenticatedSavingsRouteWithChildren,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedAccountsBankReconciliationRoute:
    AuthenticatedAccountsBankReconciliationRoute,
  AuthenticatedAccountsBulkJournalRoute: AuthenticatedAccountsBulkJournalRoute,
  AuthenticatedAccountsJournalRoute:
    AuthenticatedAccountsJournalRouteWithChildren,
  AuthenticatedAccountsPaymentsRoute:
    AuthenticatedAccountsPaymentsRouteWithChildren,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedFdIdRoute: AuthenticatedFdIdRoute,
  AuthenticatedFdMaturityRoute: AuthenticatedFdMaturityRoute,
  AuthenticatedFdNewRoute: AuthenticatedFdNewRoute,
  AuthenticatedLoansDebitNoteRoute: AuthenticatedLoansDebitNoteRoute,
  AuthenticatedLoansLegalActionRoute: AuthenticatedLoansLegalActionRoute,
  AuthenticatedLoansNewRoute: AuthenticatedLoansNewRoute,
  AuthenticatedLoansRescheduleRoute: AuthenticatedLoansRescheduleRoute,
  AuthenticatedLoansTerminationRoute: AuthenticatedLoansTerminationRoute,
  AuthenticatedLoansTransferRoute: AuthenticatedLoansTransferRoute,
  AuthenticatedLoansWriteOffRoute: AuthenticatedLoansWriteOffRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedFdIndexRoute: AuthenticatedFdIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1AtmAuthorizeRoute: ApiPublicV1AtmAuthorizeRoute,
  ApiPublicV1CeftTransferRoute: ApiPublicV1CeftTransferRoute,
  ApiPublicV1CribReportRoute: ApiPublicV1CribReportRoute,
  ApiPublicV1IbTransactionRoute: ApiPublicV1IbTransactionRoute,
  ApiPublicV1TransactionsInboundRoute: ApiPublicV1TransactionsInboundRoute,
  ApiPublicV1TransactionsOutboundRoute: ApiPublicV1TransactionsOutboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
