/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions.index'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedTransactionsRepaymentRouteImport } from './routes/_authenticated/transactions.repayment'
import { Route as AuthenticatedTransactionsPaymentsRouteImport } from './routes/_authenticated/transactions.payments'
import { Route as AuthenticatedTransactionsDisbursementRouteImport } from './routes/_authenticated/transactions.disbursement'
import { Route as AuthenticatedLoansNewRouteImport } from './routes/_authenticated/loans.new'
import { Route as AuthenticatedCollectionsNewRouteImport } from './routes/_authenticated/collections.new'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedAccountsPaymentsRouteImport } from './routes/_authenticated/accounts.payments'
import { Route as AuthenticatedAccountsJournalRouteImport } from './routes/_authenticated/accounts.journal'
import { Route as AuthenticatedAccountsPaymentsNewRouteImport } from './routes/_authenticated/accounts.payments.new'
import { Route as AuthenticatedAccountsJournalNewRouteImport } from './routes/_authenticated/accounts.journal.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsRepaymentRoute =
  AuthenticatedTransactionsRepaymentRouteImport.update({
    id: '/transactions/repayment',
    path: '/transactions/repayment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsPaymentsRoute =
  AuthenticatedTransactionsPaymentsRouteImport.update({
    id: '/transactions/payments',
    path: '/transactions/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsDisbursementRoute =
  AuthenticatedTransactionsDisbursementRouteImport.update({
    id: '/transactions/disbursement',
    path: '/transactions/disbursement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansNewRoute = AuthenticatedLoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsNewRoute =
  AuthenticatedCollectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsPaymentsRoute =
  AuthenticatedAccountsPaymentsRouteImport.update({
    id: '/accounts/payments',
    path: '/accounts/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsJournalRoute =
  AuthenticatedAccountsJournalRouteImport.update({
    id: '/accounts/journal',
    path: '/accounts/journal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsPaymentsNewRoute =
  AuthenticatedAccountsPaymentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsPaymentsRoute,
  } as any)
const AuthenticatedAccountsJournalNewRoute =
  AuthenticatedAccountsJournalNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsJournalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/accounts/journal': typeof AuthenticatedAccountsJournalRouteWithChildren
  '/accounts/payments': typeof AuthenticatedAccountsPaymentsRouteWithChildren
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/transactions/disbursement': typeof AuthenticatedTransactionsDisbursementRoute
  '/transactions/payments': typeof AuthenticatedTransactionsPaymentsRoute
  '/transactions/repayment': typeof AuthenticatedTransactionsRepaymentRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/loans/': typeof AuthenticatedLoansIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/accounts/journal/new': typeof AuthenticatedAccountsJournalNewRoute
  '/accounts/payments/new': typeof AuthenticatedAccountsPaymentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/accounts/journal': typeof AuthenticatedAccountsJournalRouteWithChildren
  '/accounts/payments': typeof AuthenticatedAccountsPaymentsRouteWithChildren
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/transactions/disbursement': typeof AuthenticatedTransactionsDisbursementRoute
  '/transactions/payments': typeof AuthenticatedTransactionsPaymentsRoute
  '/transactions/repayment': typeof AuthenticatedTransactionsRepaymentRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/accounts/journal/new': typeof AuthenticatedAccountsJournalNewRoute
  '/accounts/payments/new': typeof AuthenticatedAccountsPaymentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/accounts/journal': typeof AuthenticatedAccountsJournalRouteWithChildren
  '/_authenticated/accounts/payments': typeof AuthenticatedAccountsPaymentsRouteWithChildren
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/_authenticated/loans/new': typeof AuthenticatedLoansNewRoute
  '/_authenticated/transactions/disbursement': typeof AuthenticatedTransactionsDisbursementRoute
  '/_authenticated/transactions/payments': typeof AuthenticatedTransactionsPaymentsRoute
  '/_authenticated/transactions/repayment': typeof AuthenticatedTransactionsRepaymentRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/accounts/journal/new': typeof AuthenticatedAccountsJournalNewRoute
  '/_authenticated/accounts/payments/new': typeof AuthenticatedAccountsPaymentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/collections'
    | '/dashboard'
    | '/ledger'
    | '/reports'
    | '/accounts/journal'
    | '/accounts/payments'
    | '/clients/$id'
    | '/clients/new'
    | '/collections/new'
    | '/loans/new'
    | '/transactions/disbursement'
    | '/transactions/payments'
    | '/transactions/repayment'
    | '/clients/'
    | '/groups/'
    | '/loans/'
    | '/transactions/'
    | '/accounts/journal/new'
    | '/accounts/payments/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/collections'
    | '/dashboard'
    | '/ledger'
    | '/reports'
    | '/accounts/journal'
    | '/accounts/payments'
    | '/clients/$id'
    | '/clients/new'
    | '/collections/new'
    | '/loans/new'
    | '/transactions/disbursement'
    | '/transactions/payments'
    | '/transactions/repayment'
    | '/clients'
    | '/groups'
    | '/loans'
    | '/transactions'
    | '/accounts/journal/new'
    | '/accounts/payments/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/ledger'
    | '/_authenticated/reports'
    | '/_authenticated/accounts/journal'
    | '/_authenticated/accounts/payments'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/collections/new'
    | '/_authenticated/loans/new'
    | '/_authenticated/transactions/disbursement'
    | '/_authenticated/transactions/payments'
    | '/_authenticated/transactions/repayment'
    | '/_authenticated/clients/'
    | '/_authenticated/groups/'
    | '/_authenticated/loans/'
    | '/_authenticated/transactions/'
    | '/_authenticated/accounts/journal/new'
    | '/_authenticated/accounts/payments/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/repayment': {
      id: '/_authenticated/transactions/repayment'
      path: '/transactions/repayment'
      fullPath: '/transactions/repayment'
      preLoaderRoute: typeof AuthenticatedTransactionsRepaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/payments': {
      id: '/_authenticated/transactions/payments'
      path: '/transactions/payments'
      fullPath: '/transactions/payments'
      preLoaderRoute: typeof AuthenticatedTransactionsPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/disbursement': {
      id: '/_authenticated/transactions/disbursement'
      path: '/transactions/disbursement'
      fullPath: '/transactions/disbursement'
      preLoaderRoute: typeof AuthenticatedTransactionsDisbursementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/new': {
      id: '/_authenticated/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof AuthenticatedLoansNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections/new': {
      id: '/_authenticated/collections/new'
      path: '/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof AuthenticatedCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/payments': {
      id: '/_authenticated/accounts/payments'
      path: '/accounts/payments'
      fullPath: '/accounts/payments'
      preLoaderRoute: typeof AuthenticatedAccountsPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/journal': {
      id: '/_authenticated/accounts/journal'
      path: '/accounts/journal'
      fullPath: '/accounts/journal'
      preLoaderRoute: typeof AuthenticatedAccountsJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/payments/new': {
      id: '/_authenticated/accounts/payments/new'
      path: '/new'
      fullPath: '/accounts/payments/new'
      preLoaderRoute: typeof AuthenticatedAccountsPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedAccountsPaymentsRoute
    }
    '/_authenticated/accounts/journal/new': {
      id: '/_authenticated/accounts/journal/new'
      path: '/new'
      fullPath: '/accounts/journal/new'
      preLoaderRoute: typeof AuthenticatedAccountsJournalNewRouteImport
      parentRoute: typeof AuthenticatedAccountsJournalRoute
    }
  }
}

interface AuthenticatedCollectionsRouteChildren {
  AuthenticatedCollectionsNewRoute: typeof AuthenticatedCollectionsNewRoute
}

const AuthenticatedCollectionsRouteChildren: AuthenticatedCollectionsRouteChildren =
  {
    AuthenticatedCollectionsNewRoute: AuthenticatedCollectionsNewRoute,
  }

const AuthenticatedCollectionsRouteWithChildren =
  AuthenticatedCollectionsRoute._addFileChildren(
    AuthenticatedCollectionsRouteChildren,
  )

interface AuthenticatedAccountsJournalRouteChildren {
  AuthenticatedAccountsJournalNewRoute: typeof AuthenticatedAccountsJournalNewRoute
}

const AuthenticatedAccountsJournalRouteChildren: AuthenticatedAccountsJournalRouteChildren =
  {
    AuthenticatedAccountsJournalNewRoute: AuthenticatedAccountsJournalNewRoute,
  }

const AuthenticatedAccountsJournalRouteWithChildren =
  AuthenticatedAccountsJournalRoute._addFileChildren(
    AuthenticatedAccountsJournalRouteChildren,
  )

interface AuthenticatedAccountsPaymentsRouteChildren {
  AuthenticatedAccountsPaymentsNewRoute: typeof AuthenticatedAccountsPaymentsNewRoute
}

const AuthenticatedAccountsPaymentsRouteChildren: AuthenticatedAccountsPaymentsRouteChildren =
  {
    AuthenticatedAccountsPaymentsNewRoute:
      AuthenticatedAccountsPaymentsNewRoute,
  }

const AuthenticatedAccountsPaymentsRouteWithChildren =
  AuthenticatedAccountsPaymentsRoute._addFileChildren(
    AuthenticatedAccountsPaymentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedAccountsJournalRoute: typeof AuthenticatedAccountsJournalRouteWithChildren
  AuthenticatedAccountsPaymentsRoute: typeof AuthenticatedAccountsPaymentsRouteWithChildren
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedLoansNewRoute: typeof AuthenticatedLoansNewRoute
  AuthenticatedTransactionsDisbursementRoute: typeof AuthenticatedTransactionsDisbursementRoute
  AuthenticatedTransactionsPaymentsRoute: typeof AuthenticatedTransactionsPaymentsRoute
  AuthenticatedTransactionsRepaymentRoute: typeof AuthenticatedTransactionsRepaymentRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedAccountsJournalRoute:
    AuthenticatedAccountsJournalRouteWithChildren,
  AuthenticatedAccountsPaymentsRoute:
    AuthenticatedAccountsPaymentsRouteWithChildren,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedLoansNewRoute: AuthenticatedLoansNewRoute,
  AuthenticatedTransactionsDisbursementRoute:
    AuthenticatedTransactionsDisbursementRoute,
  AuthenticatedTransactionsPaymentsRoute:
    AuthenticatedTransactionsPaymentsRoute,
  AuthenticatedTransactionsRepaymentRoute:
    AuthenticatedTransactionsRepaymentRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
